url = http://49.249.28.218:8098/

browser = chrome

username = rmgyantra
password = rmgy@9999

environment = qa

excelPath = ./src/test/resources/ninjacrm data.xlsx

screenshotPath = ./failedscreenshot/